<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-20T11:23:14 IST" name="Suite" finished-at="2023-08-20T11:23:33 IST" duration-ms="19140">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidations.loginErrorValidation()[pri:0, instance:CompanyName.Tests.ErrorValidations@38831718]" name="loginErrorValidation" class="CompanyName.Tests.ErrorValidations"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.SubmitOrder(java.util.HashMap)[pri:0, instance:CompanyName.Tests.SubmitOrderTest@72437d8d]" name="SubmitOrder" class="CompanyName.Tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2023-08-20T11:23:14 IST" name="Error Validation Test" finished-at="2023-08-20T11:23:26 IST" duration-ms="11882">
      <class name="CompanyName.Tests.ErrorValidations">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:CompanyName.Tests.ErrorValidations@38831718]" started-at="2023-08-20T11:23:14 IST" name="launchApplication" finished-at="2023-08-20T11:23:17 IST" duration-ms="2834" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:CompanyName.Tests.ErrorValidations@38831718]" started-at="2023-08-20T11:23:17 IST" name="ProductErrorValidation" finished-at="2023-08-20T11:23:19 IST" duration-ms="2299" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:CompanyName.Tests.ErrorValidations@38831718]" started-at="2023-08-20T11:23:19 IST" name="tearDown" finished-at="2023-08-20T11:23:19 IST" duration-ms="256" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:CompanyName.Tests.ErrorValidations@38831718]" started-at="2023-08-20T11:23:19 IST" name="launchApplication" finished-at="2023-08-20T11:23:21 IST" duration-ms="2311" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:CompanyName.Tests.ErrorValidations@38831718]" started-at="2023-08-20T11:23:21 IST" name="loginErrorValidation" finished-at="2023-08-20T11:23:22 IST" duration-ms="390" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrectemail or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrectemail or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at CompanyName.Tests.ErrorValidations.loginErrorValidation(ErrorValidations.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:CompanyName.Tests.ErrorValidations@38831718]" started-at="2023-08-20T11:23:22 IST" name="tearDown" finished-at="2023-08-20T11:23:22 IST" duration-ms="131" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:CompanyName.Tests.ErrorValidations@38831718]" started-at="2023-08-20T11:23:22 IST" name="launchApplication" finished-at="2023-08-20T11:23:24 IST" duration-ms="1698" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:CompanyName.Tests.ErrorValidations@38831718]" started-at="2023-08-20T11:23:24 IST" name="loginErrorValidation" finished-at="2023-08-20T11:23:25 IST" duration-ms="953" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrectemail or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrectemail or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at CompanyName.Tests.ErrorValidations.loginErrorValidation(ErrorValidations.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:CompanyName.Tests.ErrorValidations@38831718]" started-at="2023-08-20T11:23:25 IST" name="tearDown" finished-at="2023-08-20T11:23:26 IST" duration-ms="178" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- CompanyName.Tests.ErrorValidations -->
    </test> <!-- Error Validation Test -->
    <test started-at="2023-08-20T11:23:14 IST" name="Submit Order Test" finished-at="2023-08-20T11:23:33 IST" duration-ms="19140">
      <class name="CompanyName.Tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:CompanyName.Tests.SubmitOrderTest@72437d8d]" started-at="2023-08-20T11:23:14 IST" name="launchApplication" finished-at="2023-08-20T11:23:17 IST" duration-ms="2664" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:CompanyName.Tests.SubmitOrderTest@72437d8d]" started-at="2023-08-20T11:23:17 IST" name="SubmitOrder" data-provider="getData" finished-at="2023-08-20T11:23:23 IST" duration-ms="6292" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Ab@12345, email=ab@example.com, productName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:CompanyName.Tests.SubmitOrderTest@72437d8d]" started-at="2023-08-20T11:23:23 IST" name="tearDown" finished-at="2023-08-20T11:23:23 IST" duration-ms="228" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:CompanyName.Tests.SubmitOrderTest@72437d8d]" started-at="2023-08-20T11:23:23 IST" name="launchApplication" finished-at="2023-08-20T11:23:25 IST" duration-ms="1745" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:CompanyName.Tests.SubmitOrderTest@72437d8d]" started-at="2023-08-20T11:23:25 IST" name="SubmitOrder" data-provider="getData" finished-at="2023-08-20T11:23:30 IST" duration-ms="5374" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Ab@12345, email=ab@t.com, productName=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:CompanyName.Tests.SubmitOrderTest@72437d8d]" started-at="2023-08-20T11:23:30 IST" name="tearDown" finished-at="2023-08-20T11:23:30 IST" duration-ms="142" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:CompanyName.Tests.SubmitOrderTest@72437d8d]" started-at="2023-08-20T11:23:30 IST" name="launchApplication" finished-at="2023-08-20T11:23:32 IST" duration-ms="1669" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderHistorytest()[pri:0, instance:CompanyName.Tests.SubmitOrderTest@72437d8d]" started-at="2023-08-20T11:23:32 IST" name="orderHistorytest" finished-at="2023-08-20T11:23:33 IST" depends-on-methods="CompanyName.Tests.SubmitOrderTest.SubmitOrder" duration-ms="657" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistorytest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:CompanyName.Tests.SubmitOrderTest@72437d8d]" started-at="2023-08-20T11:23:33 IST" name="tearDown" finished-at="2023-08-20T11:23:33 IST" duration-ms="171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- CompanyName.Tests.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
